### ISSUE TITLE
Probable resource leak when performing merge revisions

### ISSUE THREAD

**Issue by gaabs** [guilhermejccavalcanti/jFSTMerge#56]
This most likely happens because BufferedReader is not properly closed at readFileContent, linked below:
https://github.com/guilhermejccavalcanti/jFSTMerge/blob/d23ec2fa82687e8728a0126285b962cf79eeef48/src/main/java/br/ufpe/cin/files/FilesManager.java#L222-L232

<br>
Stacktrace observed:

```
SEVERE: 
br.ufpe.cin.exceptions.PrintException: Unexpected error while performing print routines.
java.io.FileNotFoundException: /home/Gio/.jfstmerge/jfstmerge.statistics (Too many open files)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:367)
	at org.apache.commons.io.FileUtils.writeStringToFile(FileUtils.java:1928)
	at org.apache.commons.io.FileUtils.write(FileUtils.java:2045)
	at org.apache.commons.io.FileUtils.write(FileUtils.java:2002)
	at br.ufpe.cin.logging.LoggerStatistics.logContext(LoggerStatistics.java:62)
	at br.ufpe.cin.statistics.Statistics.compute(Statistics.java:74)
	at br.ufpe.cin.app.JFSTMerge.mergeFiles(JFSTMerge.java:203)
	at br.ufpe.cin.app.JFSTMerge.mergeDirectories(JFSTMerge.java:131)
	at br.ufpe.cin.app.JFSTMerge.mergeRevisions(JFSTMerge.java:95)
	at br.ufpe.cin.app.JFSTMerge.main(JFSTMerge.java:222)

	at br.ufpe.cin.logging.LoggerStatistics.logContext(LoggerStatistics.java:89)
	at br.ufpe.cin.statistics.Statistics.compute(Statistics.java:74)
	at br.ufpe.cin.app.JFSTMerge.mergeFiles(JFSTMerge.java:203)
	at br.ufpe.cin.app.JFSTMerge.mergeDirectories(JFSTMerge.java:131)
	at br.ufpe.cin.app.JFSTMerge.mergeRevisions(JFSTMerge.java:95)
	at br.ufpe.cin.app.JFSTMerge.main(JFSTMerge.java:222)
```

**Comment by guilhermejccavalcanti** [comment]
@gaabs I agree with the solution, but the stacktrace does not mention reading methods, only writing.
Or maybe it is just a collateral effect? That is, it crashes on writing because the reading is broken?

**Comment by pauloborba** [comment]
this is related to #25 @jvcoutinho
