### ISSUE TITLE
Crash with ClassNotFoundException

### ISSUE THREAD

**Issue by gaabs** [guilhermejccavalcanti/jFSTMerge#58]
Files involved: [java_ogplatform.zip](https://github.com/guilhermejccavalcanti/jFSTMerge/files/2453095/java_ogplatform.zip)

Stacktrace:
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/text/edits/MalformedTreeException
	at org.eclipse.jdt.core.dom.ASTConverter.convert(ASTConverter.java:1428)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.convert(CompilationUnitResolver.java:292)
	at org.eclipse.jdt.core.dom.ASTParser.internalCreateAST(ASTParser.java:1209)
	at org.eclipse.jdt.core.dom.ASTParser.createAST(ASTParser.java:809)
	at br.ufpe.cin.mergers.util.JavaCompiler.compile(JavaCompiler.java:83)
	at br.ufpe.cin.mergers.util.JavaCompiler.compile(JavaCompiler.java:40)
	at br.ufpe.cin.mergers.handlers.DuplicatedDeclarationHandler.handle(DuplicatedDeclarationHandler.java:29)
	at br.ufpe.cin.mergers.handlers.ConflictsHandler.findAndAccountDuplicatedDeclarationErrors(ConflictsHandler.java:81)
	at br.ufpe.cin.mergers.handlers.ConflictsHandler.handle(ConflictsHandler.java:28)
	at br.ufpe.cin.mergers.SemistructuredMerge.merge(SemistructuredMerge.java:57)
	at br.ufpe.cin.app.JFSTMerge.mergeFiles(JFSTMerge.java:172)
	at br.ufpe.cin.app.JFSTMerge.mergeDirectories(JFSTMerge.java:131)
	at br.ufpe.cin.app.JFSTMerge.mergeRevisions(JFSTMerge.java:95)
	at br.ufpe.cin.app.JFSTMerge.main(JFSTMerge.java:222)
Caused by: java.lang.ClassNotFoundException: org.eclipse.text.edits.MalformedTreeException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more
```

**Comment by gaabs** [comment]
Apparently, updating the `org.eclipse.jdt.core` dependency to latest version is enough to solve the issue.

https://mvnrepository.com/artifact/org.eclipse.jdt/org.eclipse.jdt.core/3.15.0
