### ISSUE TITLE
MalformedInputException on merge revisions

### ISSUE THREAD

**Issue by gaabs** [guilhermejccavalcanti/jFSTMerge#71]
Was observed on 88a48f8ca9ddfa7061f6648de6a2792659d2506b.

Stacktrace and involved revision attached below.

```
java.nio.charset.MalformedInputException: Input length = 1
br.ufpe.cin.exceptions.PrintException: Unexpected error while performing print routines.
Unable to manage merged output file!
	at br.ufpe.cin.printers.Prettyprinter.generateMergedFile(Prettyprinter.java:75)
	at br.ufpe.cin.printers.Prettyprinter.generateMergedTuple(Prettyprinter.java:98)
	at br.ufpe.cin.printers.Prettyprinter.generateMergedScenario(Prettyprinter.java:112)
	at br.ufpe.cin.app.JFSTMerge.mergeRevisions(JFSTMerge.java:139)
	at br.ufpe.cin.app.Main.main(Main.java:39)
An error occurred. See /home/gio/.jfstmerge/jfstmerge.log file for more details.
 Send the log to gjcc@cin.ufpe.br for analysis if preferable.
```

[rev_268bd_64808.zip](https://github.com/guilhermejccavalcanti/jFSTMerge/files/2597793/rev_268bd_64808.zip)

**Comment by pauloborba** [comment]
@jvcoutinho could you please check that and add a test?
